In [1]:
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.add(3,1)

4

In [12]:
np.array_equal(2,2)

True

In [15]:
import pandas as pd
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64