In [2]:
import numpy as np

In [2]:
print(np.__version__)

1.22.2


In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a=np.zeros(10)
a[3] = 1
a

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a=np.arange(10,30)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [14]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a= np.nonzero([1,2,0,0,0,4,0,6,0])
a

(array([0, 1, 5, 7]),)

In [19]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a=np.random.random((3,3,3))
a

array([[[0.55986551, 0.9469766 , 0.69062022],
        [0.46993229, 0.38522944, 0.96399386],
        [0.05262523, 0.63622156, 0.17524024]],

       [[0.95966477, 0.89429428, 0.78946081],
        [0.28768516, 0.63717627, 0.79270461],
        [0.36566919, 0.0503988 , 0.15827978]],

       [[0.47312288, 0.79635393, 0.67490068],
        [0.80841766, 0.42950984, 0.94548279],
        [0.1540648 , 0.26047432, 0.41293238]]])

In [24]:
a=np.random.random(3)
a

array([0.26655757, 0.53837187, 0.7827868 ])

In [32]:
a=np.random.random(10)
m=a.min()
m

0.020437721171916

In [33]:
a=np.random.random(10)
m=a.max()
m

0.9584174349777915

In [35]:
a=np.random.random(10)
m=a.mean()
m

0.6203951225674708

In [36]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a=np.random.uniform(0,20,10)
a

array([16.15373793,  0.17882685, 18.07329601, 14.4814391 ,  1.00650621,
        3.20894184,  5.51791118, 12.504967  ,  5.08719101, 15.21047735])

In [8]:
a=np.random.random(10)
a.sort()
a

array([0.00577029, 0.13262997, 0.25558766, 0.27677743, 0.50879844,
       0.66775532, 0.72502443, 0.75297525, 0.7691387 , 0.92499367])

In [9]:
A =np.random.randint(0,2,5) 
B =np.random.randint(0,2,5) 
equal =np.allclose(A,B) 
equal

False

In [11]:
#Create random vector of size 10 and replace the maximum value by 0
a=np.random.random(10) 
a[a.argmax()] = 0 
a

array([0.11978713, 0.03999653, 0.65988834, 0.        , 0.71342863,
       0.49013197, 0.19150606, 0.08808896, 0.18123713, 0.51586445])

In [12]:
#swap two rows of an array
a= np.arange(25).reshape(5,5) 
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
#find the most frequent value in an array
a=np.random.randint(0,10,50) 
print(np.bincount(a).argmax())

9


In [20]:
a= np.random.randn(2, 3)
a*10
a+a
a.shape
a.dtype
a

array([[ 1.08721228, -0.72888907, -0.30658436],
       [ 1.19320067, -0.27654585,  0.74644935]])

In [25]:
a1= [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(a1)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
#number dimensions
arr.ndim

2

In [27]:
arr.shape

(2, 4)

In [31]:
arr.dtype

dtype('int64')

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr1=arr[5]
arr1

5

In [42]:
arr2=arr[5:9]
arr2

array([5, 6, 7, 8])

In [46]:
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [47]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [48]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64, 12,  9])

In [49]:
#2 × 2 × 3 array
arr3d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr = np.empty((5, 4))
for i in range(5):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [53]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')